name: 'AI Attribution PR Summary'
description: 'Analyze AI attribution in PR commits and post a summary comment'
author: 'dotsetlabs'

branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for posting comments'
    required: true
    default: ${{ github.token }}
  whogitit-version:
    description: 'Version of whogitit to use (or "latest")'
    required: false
    default: 'latest'
  skip-if-no-attribution:
    description: 'Skip posting comment if no AI attribution found'
    required: false
    default: 'true'

outputs:
  has-attribution:
    description: 'Whether AI attribution was found'
    value: ${{ steps.analyze.outputs.has_data }}
  total-ai-lines:
    description: 'Total AI-generated lines'
    value: ${{ steps.analyze.outputs.total_ai }}
  ai-percentage:
    description: 'Percentage of AI involvement'
    value: ${{ steps.analyze.outputs.ai_percent }}

runs:
  using: 'composite'
  steps:
    - name: Fetch git notes
      shell: bash
      run: |
        git fetch origin refs/notes/whogitit:refs/notes/whogitit 2>/dev/null || echo "No whogitit notes found"
      continue-on-error: true

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install whogitit
      shell: bash
      run: |
        if [ "${{ inputs.whogitit-version }}" = "latest" ]; then
          cargo install whogitit || cargo install --git https://github.com/dotsetlabs/whogitit
        else
          cargo install whogitit@${{ inputs.whogitit-version }} || \
            cargo install --git https://github.com/dotsetlabs/whogitit --tag ${{ inputs.whogitit-version }}
        fi

    - name: Analyze PR commits
      id: analyze
      shell: bash
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        ${{ github.action_path }}/analyze.sh "$BASE_SHA" "$HEAD_SHA"

    - name: Post PR comment
      if: steps.analyze.outputs.has_data == 'true'
      uses: actions/github-script@v7
      env:
        TOTAL_AI: ${{ steps.analyze.outputs.total_ai }}
        TOTAL_AI_MODIFIED: ${{ steps.analyze.outputs.total_ai_modified }}
        TOTAL_HUMAN: ${{ steps.analyze.outputs.total_human }}
        TOTAL_ORIGINAL: ${{ steps.analyze.outputs.total_original }}
        COMMITS_WITH_AI: ${{ steps.analyze.outputs.commits_with_ai }}
        COMMIT_COUNT: ${{ steps.analyze.outputs.commit_count }}
        AI_PERCENT: ${{ steps.analyze.outputs.ai_percent }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const path = require('path');

          const totalAI = parseInt(process.env.TOTAL_AI) || 0;
          const totalAIMod = parseInt(process.env.TOTAL_AI_MODIFIED) || 0;
          const totalHuman = parseInt(process.env.TOTAL_HUMAN) || 0;
          const totalOriginal = parseInt(process.env.TOTAL_ORIGINAL) || 0;
          const commitsWithAI = parseInt(process.env.COMMITS_WITH_AI) || 0;
          const commitCount = parseInt(process.env.COMMIT_COUNT) || 0;
          const aiPercent = process.env.AI_PERCENT || '0';

          let commitDetails = '';
          try {
            commitDetails = fs.readFileSync('/tmp/commit_details.txt', 'utf8').trim();
          } catch (e) {}

          const pct = parseFloat(aiPercent);
          let emoji = pct >= 80 ? '🤖🤖🤖' : pct >= 50 ? '🤖🤖' : pct >= 20 ? '🤖' : '👤';

          const totalLines = totalAI + totalAIMod + totalHuman + totalOriginal;

          let body = `## ${emoji} AI Attribution Summary

          This PR contains **${commitsWithAI}** of **${commitCount}** commits with AI-assisted changes.

          ### Overview

          | Metric | Lines | Percentage |
          |--------|------:|----------:|
          | 🟢 AI-generated | ${totalAI} | ${totalLines > 0 ? ((totalAI / totalLines) * 100).toFixed(1) : 0}% |
          | 🟡 AI-modified by human | ${totalAIMod} | ${totalLines > 0 ? ((totalAIMod / totalLines) * 100).toFixed(1) : 0}% |
          | 🔵 Human-added | ${totalHuman} | ${totalLines > 0 ? ((totalHuman / totalLines) * 100).toFixed(1) : 0}% |
          | ⚪ Original/unchanged | ${totalOriginal} | ${totalLines > 0 ? ((totalOriginal / totalLines) * 100).toFixed(1) : 0}% |
          | **Total** | **${totalLines}** | **100%** |

          **AI involvement: ${aiPercent}%** of changed lines
          `;

          if (commitDetails) {
            body += `
          ### Commits with AI Attribution

          | Commit | Message | AI | Modified | Human | Files |
          |--------|---------|---:|--------:|------:|------:|
          ${commitDetails}
          `;
          }

          body += `
          ---
          <sub>Generated by [whogitit](https://github.com/dotsetlabs/whogitit)</sub>
          `;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(c =>
            c.user.type === 'Bot' && c.body.includes('AI Attribution Summary')
          );

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }

    - name: No attribution message
      if: steps.analyze.outputs.has_data != 'true' && inputs.skip-if-no-attribution != 'true'
      shell: bash
      run: echo "No AI attribution data found in PR commits."
